spring:
  application:
    name: itoken-service-sso
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1 #初始化建立连接个数
      min-idle: 1  #最小连接池的数量
      max-active: 20 #最大的活动的数量
      test-on-borrow: true # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      driver-class-name: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
        url: http://localhost:8084
  zikpin:
    base-url: http://localhost:9411
  tymeleaf:
    cache: false #开发时关闭缓存，不然没法看到实时预警
    mode: LEGACYHTML5 #用非严格的Html
    encoding: UTF-8
    servlet:
      content-type: text/html

mybatis:
  type-aliases-package: com.kaysanshi.itoken.common.domain
  mapper-localtions: classpath*:mapper/*.xml


server:
  port: 8503

  #熔断器#
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/





management:
  endpoint:
    health:
      show-detail: always
  endpoints:
    web:
      exposure:
        include: health,info



