spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://localhost:8084
  zikin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

#zuul:
#  routes:
#    backend-admin:
#      path: /backend/admin/**
#      serviceId: itoken-web-admin
#    backend-posts:
#      path: /backend/posts/**
#      serviceId: itoken-web-posts